### ISSUE TITLE
Github profile URL

### ISSUE THREAD

**Issue by lukethacoder** [AshutoshDash1999/Ashutosh-Dash-portfolio#2]
Hey mate.

just a friendly heads up your github profile url is pointing to the wrong place.

[ashutosh-dash.netlify.app](https://ashutosh-dash.netlify.app/) instead of [ashutoshdash.netlify.app](https://ashutoshdash.netlify.app/)

**Comment by AshutoshDash1999** [comment]
ohh, thanks a lot @lukethacoder.
I just saw that, thanks for pointing out. I have done the necessary changes.
